config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
	devise_for :students, controllers: { sessions: 'students/sessions' }
	devise_for :teachers, skip: :registrations, controllers: { sessions: 'teachers/sessions' }

	resources :departments
	resources :students
	resources :teachers

	get 'welcome/index'
	
	authenticated :student do
		root 'survey_results#new', as: :authenticated_student_dashboard
	end

	authenticated :teacher do
		root 'dashboard#index', as: :dashboard
		# root 'departments#index', as: :authenticated_teacher_dashboard
	end

	root 'welcome#index'

	resources :survey_forms
  	resources :survey_results
  	post 'create_survey_result' => 'survey_results#create_survey_result'
end

app/models/survey_result.rb
class SurveyResult < ApplicationRecord
	belongs_to :survey_form
	belongs_to :student
end

app/controllers/survey_results_controller.rb
class SurveyResultsController < ApplicationController
  before_action :set_survey_result, only: [:show, :edit, :update, :destroy]

  # GET /survey_results
  # GET /survey_results.json
  def index
    # @survey_results = SurveyResult.where(department_id: current_teacher.department_id)
    @survey_results = []
    @surveys = current_teacher.department.survey_forms
    @surveys.each  do |s|
      s.survey_results.each do |r|
        @survey_results << r
      end
    end 
    # inspect params
  end

  # GET /survey_results/1
  # GET /survey_results/1.json
  def show
  end

  # GET /survey_results/new
  def new
    # inspect params
    @survey_result = SurveyResult.new
    dept_id = current_student.department_id
    @survey_list = SurveyForm.where(department_id: dept_id, class_name: current_student.class_name).pluck(:name)
    if params[:class_survey_name].present?
      @survey_form = SurveyForm.find_by(department_id: dept_id, name: params[:class_survey_name])
      if @survey_form.present?
        @survey_form_id = @survey_form.id
        @questions = @survey_form.question
      end
    end
  end

  def create_survey_result
    @survey_form = SurveyForm.find_by(department_id: current_student.department_id, name: params[:class_survey_name])
    if @survey_form.present?
      @questions = @survey_form.question
    end
    # inspect params
    result = {}
    # questions = params[:questions].split("  ").reject { |c| c.empty? }
    @questions.each_with_index do |q,i|
      if i < 8
        result[q] = params["rating_#{i}"]
      else  
        result[q] =  params["#{q.strip}"]
      end 
    end
    puts result
    # inspect result
    survey_result = SurveyResult.create(survey_form_id: params[:survey_form_id].to_i, student_id: current_student.id, class_name: current_student.class_name, result: result)

    respond_to do |format|
      if survey_result.save
          format.html { render :success }
          # render "success"
          # format.json { render :show, status: :created, location: @survey_result }
      else
        format.html { render :new }
        format.json { render json: @survey_result.errors, status: :unprocessable_entity }
      end
    end 
  end

  # GET /survey_results/1/edit
  def edit
  end

  # POST /survey_results
  # POST /survey_results.json
  def create
    @survey_result = SurveyResult.new(survey_result_params)

    respond_to do |format|
      if @survey_result.save
        format.html { redirect_to @survey_result, notice: 'Survey result was successfully created.' }
        format.json { render :show, status: :created, location: @survey_result }
      else
        format.html { render :new }
        format.json { render json: @survey_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_results/1
  # PATCH/PUT /survey_results/1.json
  def update
    respond_to do |format|
      if @survey_result.update(survey_result_params)
        format.html { redirect_to @survey_result, notice: 'Survey result was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_result }
      else
        format.html { render :edit }
        format.json { render json: @survey_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_results/1
  # DELETE /survey_results/1.json
  def destroy
    @survey_result.destroy
    respond_to do |format|
      format.html { redirect_to survey_results_url, notice: 'Survey result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_result
      @survey_result = SurveyResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_result_params
      params.require(:survey_result).permit(:survey_form_id, :result, :student_id, :class)
    end
end

app/helpers/survey_results_helper.rb
module SurveyResultsHelper
end

app/views/survey_results/_form.html.erb
<%= form_with(model: survey_result, local: true) do |form| %>
  <% if survey_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey_result.errors.count, "error") %> prohibited this survey_result from being saved:</h2>

      <ul>
      <% survey_result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :class %>
    <%= form.text_field :class %>
  </div>

  <div class="field">
    <%= form.label :department_id %>
    <%= form.select :department_id, options_for_select(Department.all, "id", "name") %>
    <%=form.error_span(:department_id) %>
  </div>

  <!-- <div class="form-group">
    <%= f.label :department_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :department_id, options_from_collection_for_select(Department.all, "id", "name"), :class => 'form-control' %>
    </div>
    <%=f.error_span(:department_id) %>
  </div> -->

  <div class="field">
    <%= form.label :result %>
    <%= form.text_field :result %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/survey_results/_survey_form.html.erb
<% if @survey_form_id.present? %>
  <h2 style="margin-top: 40px;"><%= @survey_form.name %></h2>
    
  <%= form_tag(controller: "survey_results", action: "create_survey_result", method: "post", :html => { :class => "form-horizontal teacher" } ) do %>
    <% if survey_result.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(survey_result.errors.count, "error") %> prohibited this survey_result from being saved:</h2>

        <ul>
        <% survey_result.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= hidden_field_tag :class_survey_name, params[:class_survey_name] %>
    <%= hidden_field_tag :survey_form_id, @survey_form_id %>
    <%= hidden_field_tag :questions, @questions %>
    
    <% @questions.each_with_index do |q, index| %>
      <% if index < 8 %>
        <div class="form-group">
          <%= label_tag "#{q.strip}", q, :class => 'control-label col-lg-6' %>
            <div class="col-lg-16">
              <p>
                <!--<b>Rating</b><br/>-->
                <%= radio_button_tag "rating_#{index}", 'A' %> Excellent
                <%= radio_button_tag "rating_#{index}", 'B' %> Good
                <%= radio_button_tag "rating_#{index}", 'C' %> Fair  
                <%= radio_button_tag "rating_#{index}", 'D' %> Bad  
                <!--<%= radio_button_tag "rating_#{index}", 'E' %> E-->
            </p>

              <!--<%= text_field_tag "#{q.strip}", '', {:class => 'form-control'} %>-->
            </div>
            </divs>
        <% else %>
          <div class="form-group">
            <%= label_tag "#{q.strip}", q, :class => 'control-label col-lg-6' %>
            <%= text_area_tag "#{q.strip}", '', {:class => 'form-control'} %>
          </div>
        <% end %>
      <br/>
    <% end %>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= submit_tag "Submit", :class => 'btn btn-primary' %>
      </div>
    </div>
    <br><br>
  <% end %>
<% else %>
  <h4 style="color:red;">No survery form for your class.</h4>
<% end %>

app/views/survey_results/edit.html.erb
<h2>Editing Survey Result</h2>

<%= render 'form', survey_result: @survey_result %>

<%= link_to 'Show', @survey_result %> |
<%= link_to 'Back', survey_results_path %>

app/views/survey_results/index.html.erb
<p id="notice"><%= notice %></p>


<h2 style="margin-top: 40px;">Survey Results</h2>

<% if @survey_results.present? %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Student</th>
      <th>Survey Name</th>
      <th>Class Name</th>
      <th>Department</th>
      <th>Result</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @survey_results.each do |survey_result| %>
      <tr>
        <td><%= survey_result.student.name %></td>
        <td><%= survey_result.survey_form.name %></td>
        <td><%= survey_result.student.class_name %></td>
        <td><%= survey_result.survey_form.department.name %></td>
        <td><%= survey_result.result %></td>
        <td><%= link_to 'Show', survey_result,  :class => 'btn btn-default btn-xs' %>
        <%#= link_to 'Edit', edit_survey_result_path(survey_result), :class => 'btn btn-default btn-xs' %>
        <%= link_to 'Destroy', survey_result, method: :delete, data: { confirm: 'Are you sure?' },  :class => 'btn btn-xs btn-danger'%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% end -%>

<!--<%= link_to 'New Survey Result', new_survey_result_path %>

app/views/survey_results/new.html.erb
<br><br><br>
<%= form_tag(new_survey_result_path, method: :get, class: 'form-inline') do %>
  <div class="form-group">
    <%= select_tag :class_survey_name, options_for_select(@survey_list, params[:class_survey_name]), include_blank: "", class: 'form-control' %>
  </div>
  <%= submit_tag 'Search', :class => "btn btn-primary" %>
<% end %>

<%= render 'survey_form', survey_result: @survey_result %>

<!--<%= link_to 'Back', survey_results_path %>-->

app/views/survey_results/show.html.erb
<br><br><br>
<p id="notice"><%= notice %></p>

<dl class="dl-horizontal">

 <dt><strong>Student:</strong></dt>
 <dd><%= @survey_result.student_id %></dd>

 <dt><strong>Class:</strong></dt>
 <dd><%= @survey_result.class %></dd>

 <dt><strong>Department:</strong></dt>
 <dd><%= @survey_result.survey_form.department.name %></dd>

  <dt><strong>Result:</strong></dt>
  <dd><%= @survey_result.result %></dd>
 
</dl>

<%= link_to 'Edit', edit_survey_result_path(@survey_result) %> |
<%= link_to 'Back', survey_results_path %>

app/views/survey_results/success.html.erb
<br><br><br>

<p style="color:green;">Successfully submitted.</p>