config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
	devise_for :students, controllers: { sessions: 'students/sessions' }
	devise_for :teachers, skip: :registrations, controllers: { sessions: 'teachers/sessions' }

	resources :departments
	resources :students
	resources :teachers

	get 'welcome/index'
	
	authenticated :student do
		root 'survey_results#new', as: :authenticated_student_dashboard
	end

	authenticated :teacher do
		root 'dashboard#index', as: :dashboard
		# root 'departments#index', as: :authenticated_teacher_dashboard
	end

	root 'welcome#index'

	resources :survey_forms
  	resources :survey_results
  	post 'create_survey_result' => 'survey_results#create_survey_result'
end

app/controllers/survey_forms_controller.rb
class SurveyFormsController < ApplicationController
  before_action :set_survey_form, only: [:show, :edit, :update, :destroy]

  # GET /survey_forms
  # GET /survey_forms.json
  def index
    @survey_forms = SurveyForm.all
  end

  # GET /survey_forms/1
  # GET /survey_forms/1.json
  def show
  end

  # GET /survey_forms/new
  def new
    @survey_form = SurveyForm.new
    if params[:year].present?
      @survey_form = Student.where(class_name: params[:year])
    end
  end

  # GET /survey_forms/1/edit
  def edit
    # inspect @survey_form
    @survey_form.question = @survey_form.question.join(',')
  end

  # POST /survey_forms
  # POST /survey_forms.json
  def create
    @survey_form = SurveyForm.new(survey_form_params)
    sf = SurveyForm.create(name: @survey_form.name, class_name: @survey_form.class_name, 
      department_id: @survey_form.department_id, question: @survey_form.question.split(","))
    respond_to do |format|
      if sf
        format.html { redirect_to @survey_form, notice: 'Survey form was successfully created.' }
        format.json { render :show, status: :created, location: @survey_form }
      else
        format.html { render :new }
        format.json { render json: @survey_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /survey_forms/1
  # PATCH/PUT /survey_forms/1.json
  def update
    questions = []
    params[:survey_form][:question].split(",").each do |q|
      questions << q.strip
    end
    sf = @survey_form.update(name: params[:survey_form][:name], class_name: params[:survey_form][:class_name], 
      department_id: params[:survey_form][:department_id], question: questions)
    respond_to do |format|
      if sf
        format.html { redirect_to @survey_form, notice: 'Survey form was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey_form }
      else
        format.html { render :edit }
        format.json { render json: @survey_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /survey_forms/1
  # DELETE /survey_forms/1.json
  def destroy
    @survey_form.destroy
    respond_to do |format|
      format.html { redirect_to survey_forms_url, notice: 'Survey form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey_form
      @survey_form = SurveyForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_form_params
      params.require(:survey_form).permit(:name, :description, :question, :department_id, :class_name)
    end
end

app/helpers/survey_forms_helper.rb
module SurveyFormsHelper
end

app/views/survey_forms/_form.html.erb
<%= form_for @survey_form, :html => { :class => "form-horizontal survey_form" } do |f| %>

  <% if @survey_form.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@survey_form.errors.count, "error") %> prohibited this survey_form from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @survey_form.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>

  <div class="form-group">
    <%= f.label :class_name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select(:class_name, options_for_select(['1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year', '6th Year'],["1st Year"])) %>
      
    </div>
    <%=f.error_span(:class_name) %>
  </div>
  <div class="form-group">
    <%= f.label :question, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :question, :class => 'form-control' %>
    </div>
    <%=f.error_span(:question) %>
  </div>
  <div class="form-group">
    <%= f.label :department_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :department_id, options_from_collection_for_select(Department.all, "id", "name"), :class => 'form-control' %>
    </div>
    <%=f.error_span(:department_id) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                survey_forms_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/survey_forms/edit.html.erb
<%- model_class = SurveyForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/survey_forms/index.html.erb
<%- model_class = SurveyForm -%>
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_survey_form_path,
            :class => 'btn btn-primary' %>

  <!--<%= form_tag(students_path, method: :get, class: 'form-inline') do %>
  <div class="form-group">
    <%= select_tag "year", options_for_select(['1st Year', '2nd Year', '3rd Year', '4th Year', '5th Year', '6th Year'], params[:year]), include_blank: "All", class: 'form-control' %>
  </div>
  <%= submit_tag 'Search', :class => "btn btn-primary" %>
<% end %>-->

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:class_name) %></th>
      <th><%= model_class.human_attribute_name(:question) %></th>
      <th><%= model_class.human_attribute_name(:department_id) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @survey_forms.each do |survey_form| %>
      <tr>
        <!-- <td><%= link_to survey_form.id, survey_form_path(survey_form) %></td> -->
        <td><%= survey_form.name %></td>
        <td><%= survey_form.class_name %></td>
        <td><%= survey_form.question %></td>
        <td><%= Department.find(survey_form.department_id).name %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      survey_form_path(survey_form), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_survey_form_path(survey_form), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      survey_form_path(survey_form),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/survey_forms/new.html.erb
<%- model_class = SurveyForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/survey_forms/show.html.erb
<%- model_class = SurveyForm -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @survey_form.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:class_name) %>:</strong></dt>
  <dd><%= @survey_form.class_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:question) %>:</strong></dt>
  <dd><%= @survey_form.question %></dd>
  <dt><strong><%= model_class.human_attribute_name(:department_id) %>:</strong></dt>
  <dd><%= @survey_form.department_id %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              survey_forms_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_survey_form_path(@survey_form), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              survey_form_path(@survey_form),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>