config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
	devise_for :students, controllers: { sessions: 'students/sessions' }
	devise_for :teachers, skip: :registrations, controllers: { sessions: 'teachers/sessions' }

	resources :departments
	resources :students
	resources :teachers

	get 'welcome/index'
	
	authenticated :student do
		root 'survey_results#new', as: :authenticated_student_dashboard
	end

	authenticated :teacher do
		root 'dashboard#index', as: :dashboard
		# root 'departments#index', as: :authenticated_teacher_dashboard
	end

	root 'welcome#index'

	resources :survey_forms
  	resources :survey_results
  	post 'create_survey_result' => 'survey_results#create_survey_result'
end

app/views/layouts/_home_menu.html.erb
<div class="navbar navbar-default navbar-static-top" >
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">StudentsEvaluationSurvey</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign in", new_student_session_path  %></li>
        <li><%= link_to "Sign up", new_student_registration_path  %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_student_menu.html.erb
<div class="navbar navbar-default navbar-static-top" >
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">StudentsEvaluationSurvey</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "Log out", destroy_student_session_path, :method => :delete  %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_teacher_menu.html.erb
<div class="navbar navbar-default navbar-static-top" >
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">StudentsEvaluationSurvey</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li class="active"></li>
        <li><%= link_to "Dashboard", dashboard_path  %></li>
      	<li><%= link_to "Department", departments_path  %></li>
      	<li><%= link_to "Teacher", teachers_path  %></li>
        <li><%= link_to "Student", students_path  %></li>
        <li><%= link_to "Survey Form", survey_forms_path %></li>
        <li><%= link_to "Survey Result", survey_results_path %></li>
        <li><%= link_to "Log out", destroy_teacher_session_path, :method => :delete  %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StudentsEvaluationSurvey" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <% if student_signed_in? %>
      <%= render "layouts/student_menu" %>
    <% elsif teacher_signed_in? %>
      <%= render "layouts/teacher_menu" %>
    <% else %>
      <%= render "layouts/home_menu" %>
    <% end %>
    
    <div class="container-fluid">
          <%= bootstrap_flash %>
          <%= yield %>
    </div> 
        

      <footer style="text-align: center; background: #87CEEB;height: 50px;padding-top: 15px;color: white;">
        <p>&copy; Students Evaluation Survey 2019</p>
      </footer>

      

    </div> <!-- /container -->

  </body>
</html>